joint_names: [right_arm_1_joint, right_arm_2_joint, right_arm_3_joint, right_arm_4_joint, right_arm_5_joint, right_arm_6_joint, right_arm_7_joint]
arm_select: 'right'
loop_rate: 150.0
timeout: 30.0 #[seconds]
force_gain: 0.002
torque_gain: 0.03
v_limit: 0.08  #linear velocity limit [m/s] 
w_limit: 0.3 # angular velocity limit [rad/s]